## 

## 

In [2]:
list = [1,2]
list2 = [3,4]
list3 = list + list2
print(list3)

[1, 2, 3, 4]


In [9]:
matrix1 = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
matrix2 = np.array([[14,15,16],[23,24,25],[34,35,36],[44,45,46]])
matrix3  = matrix1 + matrix2 
print(matrix3)


[[25 27 29]
 [44 46 48]
 [65 67 69]
 [85 87 89]]


In [5]:
print(matrix3)

[[11, 12, 13], [21, 22, 23], [31, 32, 33], [14, 15, 16], [23, 24, 25], [34, 35, 36]]
